name: C/C++ CI on Ubuntu

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
    - build/*
  pull_request:
    branches:
    - master
    - build/*
  schedule:
  - cron: 0 2 * * 1-5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build on ${{ matrix.os }} ${{ matrix.config }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        config: [release]
        os: [ubuntu-1604, ubuntu-1804, ubuntu-2004]    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      env:
      run: tools/build.sh ${{ matrix.config }}
    - name: Test
      run: ./tools/run-tests-all.sh
