name: otel_sdk

# Example:
#  git tag -a v1.14.2.dll.x -m "Release 1.14.2.dll.x" && git push --tags
on:
  push:
    tags:
      - "*"
    branches:
      - main
jobs:
  otel_sdk_build:
    name: build otel_sdk
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - run: ls env:* | Format-Table -AutoSize
      - run: choco install bazelisk
      - run: choco upgrade llvm --version 18.1.0
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: d:/d.vhdx
          enableCrossOsArchive: true
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel', 'MODULE.bazel.lock') }}
          restore-keys: ${{ runner.os }}-bazel-
      - name: mount cache disk
        run: |
          $mount = "d:/d"
          $vhd = New-VHD -Path "d:/d.vhdx" -SizeBytes 137438953472 -Dynamic -LogicalSectorSizeBytes 512 -PhysicalSectorSizeBytes 512 -Verbose
          $vhd
          Mount-VHD -Path $vhd.path -Verbose
          $disk = Get-VHD -Path $vhd.path -Verbose
          $disk
          Initialize-Disk $disk.Number -Verbose
          $part = New-Partition -DiskNumber $disk.Number -UseMaximumSize -Verbose
          $part
          $vol = Format-Volume -FileSystem REFS -Partition $part -Verbose
          $vol
          New-Item -Path $mount -ItemType "directory" -Force -Verbose
          $part | Add-PartitionAccessPath -AccessPath $mount -Verbose
      - name: test otel_sdk
        run: |
          echo "build --disk_cache=d:/d" > ../top.bazelrc
          echo "common --repository_cache=d:/r" >> ../top.bazelrc
          echo "startup --output_user_root=d:/b" >> ../top.bazelrc
          ./otel_sdk_build.cmd test
          ./otel_sdk_build.cmd shutdown
      - run: Dismount-VHD -Path "d:/d.vhdx" -Verbose
      - uses: actions/cache/save@v4
        # Don't update cache on releases
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          path: d:/d.vhdx
          enableCrossOsArchive: true
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel', 'MODULE.bazel.lock') }}
      - run: |
          $mnt = Mount-VHD -Path "d:/d.vhdx" -Verbose
          $mnt
      - uses: actions/upload-artifact@v4
        with:
          name: tracing-profiles
          path: ./*.tracing.json
          if-no-files-found: warn
      - name: build otel_sdk.zip
        run: |
          ./otel_sdk_build.cmd zip
          ./otel_sdk_build.cmd shutdown
      - uses: actions/upload-artifact@v4
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          name: sdk
          path: ./otel_sdk.zip
          if-no-files-found: warn
      - name: release otel_sdk.zip
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: ncipollo/release-action@v1
        with: # skipping as test nodll ./0.nodll.tracing.json
          artifacts: |
            ./otel_sdk.zip
            ./1.all.tracing.json
            ./2.dbg.tracing.json
            ./3.fastbuild.tracing.json
            ./4.opt.tracing.json
            ./5.pkg.tracing.json
