name: otel_sdk

# Example:
#  git tag -a v1.14.2.dll.x -m "Release 1.14.2.dll.x" && git push --tags
on:
  push:
    tags:
      - "*"
    branches:
      - main
jobs:
  otel_sdk_build:
    name: build otel_sdk
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - run: ls env:* | Format-Table -AutoSize
      - run: choco install bazelisk
      - run: choco upgrade llvm --version 18.1.0
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: d:/d
          enableCrossOsArchive: true
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel', 'MODULE.bazel.lock') }}
          restore-keys: ${{ runner.os }}-bazel-
      - name: run otel_sdk_build.cmd
        run: |
          echo "build --disk_cache=d:/d" > ../top.bazelrc
          echo "common --repository_cache=d:/r" >> ../top.bazelrc
          echo "startup --output_user_root=d:/b" >> ../top.bazelrc
      - name: stamp version
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: $rev = git rev-parse HEAD; echo "__declspec(dllexport) const char* otelsdk_gitsha(){ return `"$rev`"; }" > version.c
      - run: ./otel_sdk_build.cmd test
      - uses: actions/upload-artifact@v4
        with:
          name: tracing-profiles
          path: ./*.tracing.json
          if-no-files-found: warn
      - uses: actions/cache/save@v4
        with:
          path: d:/d
          enableCrossOsArchive: true
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel', 'MODULE.bazel.lock') }}
      - name: build otel_sdk.zip
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: ./otel_sdk_build.cmd
      - name: release otel_sdk.zip
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: ncipollo/release-action@v1
        with: # skipping as test nodll ./0.nodll.tracing.json
          artifacts: |
            ./otel_sdk.zip
            ./1.all.tracing.json
            ./2.dbg.tracing.json
            ./3.fastbuild.tracing.json
            ./4.opt.tracing.json
            ./5.pkg.tracing.json
  